name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: XpiritBV/ActionsFundamentals-FlutterNL/.github/workflows/reusable-workflow.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      
